apiVersion: v1
kind: Service
metadata:
  name: oomvisor-frontend
  labels:
    app: oomvisor-frontend
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: oomvisor-frontend
  type: ClusterIP